apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-certificate
  namespace: nginx
spec:
  dnsNames:
    - nginx.parnamirim.rn.gov.br
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: nginx-tls
