Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
    end

    config.vm.define "node01" do |node01|
        node01.vm.hostname = "node01"
        node01.vm.network "public_network", ip: "192.168.1.100"
        node01.vm.provision "shell",
            inline: "apt update && apt -y upgrade && apt -y dist-upgrade"
        node01.vm.provision "shell",
            inline: "apt -y install mariadb-server rsync"
    end

    config.vm.define "node02" do |node02|
        node02.vm.hostname = "node02"
        node02.vm.network "public_network", ip: "192.168.1.200"
        node02.vm.provision "shell",
            inline: "apt update && apt -y upgrade && apt -y dist-upgrade"
        node02.vm.provision "shell",
            inline: "apt -y install mariadb-server rsync"
    end

    # config.vm.define "node03" do |node03|
    #     node03.vm.network "public_network", ip: "192.168.1.5"
    #     node03.vm.provision "shell",
    #         inline: "apt update && apt -y upgrade && apt -y dist-upgrade"
    #     node03.vm.provision "shell",
    #         inline: "apt -y install mariadb-server rsync"
    # end
end